version: "3"

services:
  main-db:
    image: postgres
    ports:
      - 5435:5434
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${PGPORT}
    volumes:
      - ./main-db:/var/lib/postgresql/data

volumes:
  main-db: