version: "3"

services:
  main-db:
    image: postgres
    ports:
      - 5435:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=papamama1R
      - POSTGRES_DB=bitcloud_db
      - PGPORT=5434
    volumes:
      - ./main-db:/var/lib/postgresql/data

volumes:
  main-db: