import { dmSans, inter, notoSans } from '@/globals/css'
import { Footer } from '@/widgets/footer/ui/Footer'
import { Header } from '@/widgets/header/ui/Header'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${dmSans.variable} ${notoSans.variable} ${inter.variable}`}
			>
				<div className='flex flex-col min-h-screen'>
					<Header />
					<main className='flex-grow bg-background-custom'>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
