import { dmSans, notoSans, inter } from './_lib'
import { AppProvider } from './_providers'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'BitCloud',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${dmSans.variable} ${notoSans.variable} ${inter.variable}`}
			>
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	)
}
