import { dmSans, inter, notoSans } from '@/globals/css'
import { Header } from '@/widgets/header/ui/Header'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${dmSans.variable} ${notoSans.variable} ${inter.variable}`}
			>
				<Header />
				{children}
			</body>
		</html>
	)
}
